### ISSUE TITLE
  assets/recovery_phrase.txt

### ISSUE THREAD

**Issue by teomalex** [kurtatwork/KurtAtWork-OpenSea-Auto-Uploader#2]
Why it needs   assets/recovery_phrase.txt ?
This is suspicious....

**Comment by kurtatwork** [comment]
It isn’t required that you save it as a text file. If you don’t want to enter the metamask pass in a file, You can enter the password in the terminal at the beginning of the script as well.

The only reason it’s needed at all, is how else do you think opensea Is going to be able to access your account? You log in with metamask on opensea… the selenium browser opens a new window with no user profile so your usual metamask isn’t there when the browser opens. 

At the beginning of the script, the process logs into metamask, and then once it’s logged in it logs into opensea… once it’s fully logged into opensea it begins minting and listing until done.

If you don’t want to trust it, that’s fine.
I forked this project from someone else, have used it for a while before I made modifications to it… all my cryptos and NFTs are still in my wallet. It hasn’t been hacked yet.

at the same time, I had a similar response when I first came across the original code that I ended up forking from… 

All I have to say is, if you don’t trust it, don’t do it… at least until you’ve looked over the code enough and determined whether or not you can actually trust it. That’ what i had to do…

So far all my crypto is still in my wallet.
I’m also currently uploading 5k-10k of my collection as i’m writing this.

https://opensea.io/collection/letsgobrandon-nft

I’m ok with people not wanting to use it… that’s totally fine. No pressure dude.

the script is safe though. (To my knowledge)
If you have a concern about a SPECIFIC vulnerability… please let me know.

**Comment by teomalex** [comment]
Yes you are right. The script is safe.

**Comment by kurtatwork** [comment]
and were you able to get it up and running ok?

**Comment by kurtatwork** [comment]
I'm going to go ahead and close this issue for now, If anybody has any specific issues related to this, feel free to reopen this as an open issue and add to the project.
